const products = [
  {
    'Phone & Tablets': [
      {
        id: 1,
        name: 'iPhone 14',
        primary_picture: 'https://picsum.photos/300',
        spec: ['128GB', '256GB', '512GB'],
        description:
          'The latest iPhone with A15 chip, ceramic shield front, dual camera system',
        price: '999',
      },
      {
        id: 2,
        name: 'Samsung Galaxy S23',
        primary_picture: 'https://picsum.photos/300',
        spec: ['S23', 'S23 Plus', 'S23 Ultra'],
        description:
          'Newest Samsung Galaxy flagship phone with Snapdragon 8 Gen 2 chip',
        price: '799',
      },
      {
        id: 3,
        name: 'Google Pixel 7 Pro',
        primary_picture: 'https://picsum.photos/300',
        description:
          "Google's flagship phone with Tensor G2 chip, advanced camera capabilities",
        price: '899',
      },
      {
        id: 4,
        name: 'iPad 10th Generation',
        primary_picture: 'https://picsum.photos/300',
        spec: ['64GB', '256GB'],
        description: "Apple's latest 10.9-inch iPad with A14 Bionic chip",
        price: '449',
      },
      {
        id: 5,
        name: 'Samsung Galaxy Tab S8',
        primary_picture: 'https://picsum.photos/300',
        spec: ['11-inch', '12.4-inch'],
        description:
          'Premium Samsung Galaxy tablet great for media, gaming, and multitasking',
        price: '699',
      },
      {
        id: 6,
        name: 'Amazon Fire HD 10',
        primary_picture: 'https://picsum.photos/300',
        description:
          'Affordable 10-inch tablet from Amazon, great for media consumption',
        price: '149',
      },
      {
        id: 7,
        name: 'Motorola Moto G Stylus',
        primary_picture: 'https://picsum.photos/300',
        description: 'Mid-range Motorola phone with built-in stylus',
        price: '299',
      },
      {
        id: 8,
        name: 'Nokia X30 5G',
        primary_picture: 'https://picsum.photos/300',
        description: "Nokia's new affordable 5G smartphone",
        price: '399',
      },
      {
        id: 9,
        name: 'Sony Xperia 1 IV',
        primary_picture: 'https://picsum.photos/300',
        description: 'Flagship Sony phone with 4K display, 120Hz refresh rate',
        price: '1599',
      },
      {
        id: 10,
        name: 'OnePlus 11',
        primary_picture: 'https://picsum.photos/300',
        description:
          "OnePlus's newest high-end phone with Snapdragon 8 Gen 2 chip",
        price: '699',
      },
      {
        id: 11,
        name: 'Razer Edge',
        primary_picture: 'https://picsum.photos/300',
        description: "Razer's handheld gaming tablet with Snapdragon G3x chip",
        price: '399',
      },
      {
        id: 12,
        name: 'Microsoft Surface Duo 3',
        primary_picture: 'https://picsum.photos/300',
        spec: ['128GB', '512GB'],
        description:
          'Dual-screen, folding Surface phone designed for productivity',
        price: '1099',
      },
    ],
  },
  {
    Computing: [
      {
        id: 13,
        name: 'MacBook Air M2',
        primary_picture: 'https://picsum.photos/300',
        spec: ['256GB SSD', '512GB SSD'],
        description: 'Thin and light Apple laptop powered by new M2 chip',
        price: '1199',
      },
      {
        id: 14,
        name: 'Dell XPS 15',
        primary_picture: 'https://picsum.photos/300',
        spec: ['Core i5', 'Core i7', 'Core i9'],
        description:
          'A high performance Windows laptop ideal for demanding tasks',
        price: '1299',
      },
      {
        id: 15,
        name: 'Acer Chromebook Spin 713',
        primary_picture: 'https://picsum.photos/300',
        description:
          'Convertible Chromebook with excellent build quality and performance',
        price: '629',
      },
      {
        id: 16,
        name: 'Asus ROG Zephyrus G15',
        primary_picture: 'https://picsum.photos/300',
        spec: ['RTX 3070 Ti', 'RTX 3080 Ti'],
        description: 'A super powerful Asus gaming laptop',
        price: '1949',
      },
      {
        id: 17,
        name: 'HP spectre x360',
        primary_picture: 'https://picsum.photos/300',
        description: 'Sleek HP convertible laptop with stylus support',
        price: '1199',
      },
      {
        id: 18,
        name: 'Lenovo ThinkPad X1 Carbon',
        primary_picture: 'https://picsum.photos/300',
        spec: ['Core i5', 'Core i7'],
        description:
          'Light business ultrabook known for durability and reliability',
        price: '1329',
      },
      {
        id: 19,
        name: 'Microsoft Surface Laptop 5',
        primary_picture: 'https://picsum.photos/300',
        spec: ['13.5-inch', '15-inch'],
        description:
          'The latest Surface Laptop from Microsoft, now with 12th gen Intel processors',
        price: '999',
      },
      {
        id: 20,
        name: 'LG Gram 17',
        primary_picture: 'https://picsum.photos/300',
        description:
          'A super lightweight 17-inch laptop with excellent battery life',
        price: '1399',
      },
      {
        id: 21,
        name: 'Samsung Galaxy Book 3 Pro',
        primary_picture: 'https://picsum.photos/300',
        spec: ['13.3-inch', '15.6-inch'],
        description:
          'Light and portable Samsung laptop with beautiful AMOLED display',
        price: '1199',
      },
      {
        id: 22,
        name: 'Asus Zenbook S 13 OLED',
        primary_picture: 'https://picsum.photos/300',
        description:
          'Slim and lightweight Asus ultrabook with vivid OLED screen',
        price: '1099',
      },
      {
        id: 23,
        name: 'Acer Nitro 5',
        primary_picture: 'https://picsum.photos/300',
        spec: ['RTX 3050', 'RTX 3060'],
        description: 'Affordable Acer gaming laptop',
        price: '799',
      },
      {
        id: 24,
        name: 'MSI Katana GF66',
        primary_picture: 'https://picsum.photos/300',
        spec: ['RTX 3050', 'RTX 3060'],
        description: "MSI's budget-friendly gaming laptop",
        price: '849',
      },
    ],
  },
  {
    Electronics: [
      {
        id: 25,
        name: 'Sony Bravia XR A95K',
        primary_picture: 'https://picsum.photos/300',
        spec: ['55-inch', '65-inch', '75-inch', '85-inch'],
        description: 'Cutting edge Sony OLED 4K TV with cognitive processor',
        price: '2499',
      },
      {
        id: 26,
        name: 'Samsung The Frame TV',
        primary_picture: 'https://picsum.photos/300',
        spec: ['43-inch', '50-inch', '55-inch', '65-inch', '75-inch'],
        description: 'Lifestyle TV designed to display art when not in use',
        price: '1497',
      },
      {
        id: 27,
        name: 'LG C2 Series OLED',
        primary_picture: 'https://picsum.photos/300',
        spec: ['48-inch', '55-inch', '65-inch', '77-inch', '83-inch'],
        description: 'Stunning LG OLED TV great for movies and gaming',
        price: '1296',
      },
      {
        id: 28,
        name: 'JBL Boombox',
        primary_picture: 'https://picsum.photos/300',
        description: 'Massive, powerful Bluetooth speaker with monstrous bass',
        price: '499',
      },
      {
        id: 29,
        name: 'Sonos One',
        primary_picture: 'https://example.com/sonosone.jpg',
        description: 'Compact smart speaker with great sound quality',
        price: '219',
      },
      {
        id: 30,
        name: 'Apple AirPods Pro 2',
        primary_picture: 'https://picsum.photos/300',
        description:
          'Latest noise-cancelling earbuds from Apple with touch controls',
        price: '249',
      },
      {
        id: 31,
        name: 'Bose QuietComfort Earbuds II',
        primary_picture: 'https://picsum.photos/300',
        description: "Bose's flagship noise-cancelling wireless earbuds",
        price: '299',
      },
      {
        id: 32,
        name: 'Samsung Galaxy Buds 2',
        primary_picture: 'https://picsum.photos/300',
        description:
          "Samsung's lightweight wireless earbuds with active noise cancellation",
        price: '149',
      },
      {
        id: 33,
        name: 'Canon EOS R6',
        primary_picture: 'https://picsum.photos/300',
        description:
          'Full frame mirrorless camera with 4K video and 20 FPS burst',
        price: '2499',
      },
      {
        id: 34,
        name: 'GoPro Hero 11 Black',
        primary_picture: 'https://picsum.photos/300',
        description: 'Latest action camera from GoPro with new sensor',
        price: '399',
      },
      {
        id: 35,
        name: 'Nikon Z9',
        primary_picture: 'https://picsum.photos/300',
        description:
          "Nikon's top-of-the-line full frame mirrorless sports camera",
        price: '5496',
      },
      {
        id: 36,
        name: 'DualSense Edge controller',
        primary_picture: 'https://picsum.photos/300',
        description: "PlayStation's pro controller with back buttons",
        price: '199',
      },
      {
        id: 37,
        name: 'Xbox Elite Controller Series 2',
        primary_picture: 'https://picsum.photos/300',
        description: "Xbox's pro controller designed for competitive gaming",
        price: '179',
      },
      {
        id: 38,
        name: 'Nintendo Switch Lite',
        primary_picture: 'https://picsum.photos/300',
        description: 'Portable-only Nintendo Switch console',
        price: '199',
      },
      {
        id: 39,
        name: 'Amazon Echo Show 15',
        primary_picture: 'https://picsum.photos/300',
        description: 'Large smart display for your wall from Amazon',
        price: '249',
      },
      {
        id: 40,
        name: 'Philips Hue Starter Kit',
        primary_picture: 'https://picsum.photos/300',
        description: 'Get started with smart lighting from Hue',
        price: '199',
      },
      {
        id: 41,
        name: 'iRobot Roomba j7',
        primary_picture: 'https://picsum.photos/300',
        description: 'Advanced robot vacuum that avoids pet accidents',
        price: '599',
      },
    ],
  },
  {
    Fashion: [
      {
        id: 42,
        name: "Levi's 501 Original Jeans",
        primary_picture: 'https://picsum.photos/300',
        spec: ['Skinny', 'Tapered', 'Bootcut'],
        description: "Classic straight leg denim jeans from Levi's",
        price: '59',
      },
      {
        id: 43,
        name: 'Champion Crewneck Sweatshirt',
        primary_picture: 'https://picsum.photos/300',
        description: 'Cozy fleece sweatshirt from Champion',
        price: '55',
      },
      {
        id: 44,
        name: 'Ray-Ban Aviator Sunglasses',
        primary_picture: 'https://picsum.photos/300',
        description: 'Iconic sunglasses with metal frame and lens',
        price: '163',
      },
      {
        id: 45,
        name: 'Canada Goose Expedition Parka',
        primary_picture: 'https://picsum.photos/300',
        description: 'Premium insulated winter parka built for extreme cold',
        price: '995',
      },
      {
        id: 46,
        name: 'Lululemon Align Leggings',
        primary_picture: 'https://picsum.photos/300',
        description:
          'Ultra soft, stretchy leggings great for yoga and lounging',
        price: '98',
      },
      {
        id: 47,
        name: 'UGG Fluff Yeah Slide',
        primary_picture: 'https://picsum.photos/300',
        description: 'Cozy UGG platform slide slippers with plush sheepskin',
        price: '99',
      },
      {
        id: 48,
        name: 'Columbia Waterproof Hiking Boots',
        primary_picture: 'https://picsum.photos/300',
        description: 'Durable hiking boots with waterproof construction',
        price: '139',
      },
      {
        id: 49,
        name: 'Patagonia Nano Puff Jacket',
        primary_picture: 'https://picsum.photos/300',
        description: 'Lightweight, packable, insulated jacket',
        price: '199',
      },
      {
        id: 50,
        name: 'Under Armour HOVR Running Shoes',
        primary_picture: 'https://picsum.photos/300',
        description: 'Cushioned running shoes designed for comfort',
        price: '120',
      },
      {
        id: 51,
        name: 'Gucci Ace Platform Sneakers',
        primary_picture: 'https://picsum.photos/300',
        description: 'Iconic Gucci low-top platform sneakers',
        price: '650',
      },
      {
        id: 52,
        name: 'Tory Burch Flats',
        primary_picture: 'https://picsum.photos/300',
        description:
          'Versatile ballet flats with signature Tory Burch double T logo',
        price: '228',
      },
      {
        id: 53,
        name: 'Michael Kors Tote Bag',
        primary_picture: 'https://picsum.photos/300',
        description: 'Spacious and elegant tote bag for everyday',
        price: '358',
      },
    ],
  },
  {
    'Home & Office': [
      {
        id: 54,
        name: 'Dyson V15 Cordless Vacuum',
        primary_picture: 'https://picsum.photos/300',
        description: 'Powerful, long-lasting wireless stick vacuum',
        price: '599',
      },
      {
        id: 55,
        name: 'Vitamix Ascent Series Blender',
        primary_picture: 'https://picsum.photos/300',
        description:
          'Commercial grade countertop blender with stainless steel blades',
        price: '549',
      },
      {
        id: 56,
        name: 'Nespresso Vertuo Next Coffee Machine',
        primary_picture: 'https://picsum.photos/300',
        description: 'Brew a variety of coffee sizes from Nespresso pods',
        price: '229',
      },
      {
        id: 57,
        name: 'Casper Queen Memory Foam Mattress',
        primary_picture: 'https://picsum.photos/300',
        description: 'High quality foam mattress promotes spinal alignment',
        price: '995',
      },
      {
        id: 58,
        name: 'Bissell SpinWave Wet and Dry Robot Vacuum',
        primary_picture: 'https://picsum.photos/300',
        description: 'Unique robot vac that can dry clean carpets and vacuum',
        price: '399',
      },
      {
        id: 59,
        name: 'Instant Pot Duo Plus',
        primary_picture: 'https://picsum.photos/300',
        description: '9-in-1 multi-use pressure cooker with sterilizer',
        price: '119',
      },
      {
        id: 60,
        name: 'Philips Hue White Ambiance Smart Light Bulbs',
        primary_picture: 'https://picsum.photos/300',
        description:
          'Set the mood with soft white to bright white light settings',
        price: '99',
      },
      {
        id: 61,
        name: 'Dyson Pure Cool Air Purifier',
        primary_picture: 'https://picsum.photos/300',
        description: 'Advanced air purifier and fan combo from Dyson',
        price: '749',
      },
      {
        id: 62,
        name: 'Keurig K Supremem Plus Smart Coffee Maker',
        primary_picture: 'https://picsum.photos/300',
        description: 'Make coffeehouse drinks at home',
        price: '229',
      },
      {
        id: 63,
        name: 'Microsoft Surface Headphones 2',
        primary_picture: 'https://picsum.photos/300',
        description:
          'Over-ear active noise cancelling headphones from Microsoft',
        price: '249',
      },
      {
        id: 64,
        name: 'Lenovo Smart Clock Essential',
        primary_picture: 'https://picsum.photos/300',
        description: 'Fun smart clock with Google Assistant',
        price: '49',
      },
      {
        id: 65,
        name: 'Ninja Foodi Digital Fry Oven',
        primary_picture: 'https://picsum.photos/300',
        description: 'Air fry and dehydrate with little to no oil',
        price: '129',
      },
    ],
  },
  {
    Supermarket: [
      {
        id: 66,
        name: 'Chobani Greek Yogurt',
        primary_picture: 'https://picsum.photos/300',
        spec: ['Blueberry', 'Strawberry', 'Vanilla'],
        description: 'Thick and creamy strained Greek yogurt',
        price: '4',
      },
      {
        id: 67,
        name: 'Nature Valley Granola Bars',
        primary_picture: 'https://picsum.photos/300',
        spec: ['Peanut Butter', 'Oats n Honey', 'Fruit & Nut'],
        description: 'On-the-go granola bars',
        price: '3',
      },
      {
        id: 68,
        name: 'Pepsi Cola',
        primary_picture: 'https://picsum.photos/300',
        spec: ['Regular', 'Diet', 'Zero Sugar'],
        description: 'Signature cola taste from Pepsi',
        price: '5',
      },
      {
        id: 69,
        name: 'Quaker Instant Oatmeal',
        primary_picture: 'https://picsum.photos/300',
        spec: ['Cinnamon', 'Brown Sugar', 'Strawberries'],
        description: 'Quick, delicious hot oatmeal in under 2 minutes',
        price: '4',
      },
      {
        id: 70,
        name: "Lay's Classic Potato Chips",
        primary_picture: 'https://picsum.photos/300',
        spec: ['Original Salted', 'Sour Cream', 'Cheddar'],
        description: 'Crispy potato chips',
        price: '5',
      },
      {
        id: 71,
        name: "Ben & Jerry's Ice Cream",
        primary_picture: 'https://picsum.photos/300',
        spec: ['Cherry Garcia', 'Half Baked', 'Chunky Monkey'],
        description: "Iconic Ben & Jerry's packed with chunks and swirls",
        price: '5',
      },
      {
        id: 72,
        name: 'Dove Beauty Bars',
        primary_picture: 'https://picsum.photos/300',
        description: 'Gentle moisturizing beauty bar for softer skin',
        price: '7',
      },
      {
        id: 73,
        name: "Campbell's Chicken Noodle Soup",
        primary_picture: 'https://picsum.photos/300',
        description: 'Classic chicken noodle soup to warm you up',
        price: '3',
      },
      {
        id: 74,
        name: 'Nutella Hazelnut Spread',
        primary_picture: 'https://picsum.photos/300',
        description: 'Creamy, chocolate-hazelnut spread',
        price: '7',
      },
      {
        id: 75,
        name: 'Kraft Macaroni & Cheese',
        primary_picture: 'https://picsum.photos/300',
        description: 'Crowd-pleasing mac & cheese meals and cups',
        price: '3',
      },
      {
        id: 76,
        name: 'Coca-Cola Soda',
        primary_picture: 'https://picsum.photos/300',
        spec: ['Original', 'Zero Sugar', 'Diet'],
        description: 'Refreshing, ice-cold cola',
        price: '5',
      },
      {
        id: 77,
        name: 'Wonder Bread',
        primary_picture: 'https://picsum.photos/300',
        description: 'Fluffy white bread',
        price: '4',
      },
    ],
  },
  {
    'Health & Beauty': [
      {
        id: 78,
        name: 'Cetaphil Gentle Cleanser',
        primary_picture: 'https://picsum.photos/300',
        description: 'Gentle daily cleanser for sensitive skin',
        price: '15',
      },
      {
        id: 79,
        name: 'Neutrogena Hydro Boost Moisturizer ',
        primary_picture: 'https://picsum.photos/300',
        description: 'Gel-cream face moisturizer that quenches dry skin',
        price: '19',
      },
      {
        id: 80,
        name: 'Crest 3D Whitestrips',
        primary_picture: 'https://picsum.photos/300',
        description: 'Easily whiten teeth at home',
        price: '50',
      },
      {
        id: 81,
        name: 'Olay Regenerist Micro-Sculpting Cream',
        primary_picture: 'https://picsum.photos/300',
        description: 'Anti-aging face moisturizer cream',
        price: '28',
      },
      {
        id: 82,
        name: 'Gillette Mach3 Razor',
        primary_picture: 'https://picsum.photos/300',
        description: '3 anti-friction blades for a close shave',
        price: '8',
      },
      {
        id: 83,
        name: 'Head & Shoulders Shampoo',
        primary_picture: 'https://picsum.photos/300',
        spec: ['Classic Clean', 'Royal Oils'],
        description: 'Dandruff shampoo',
        price: '6',
      },
      {
        id: 85,
        name: 'Oral-B Pro Toothbrush',
        primary_picture: 'https://picsum.photos/300',
        description: 'Rotating electric toothbrush ',
        price: '25',
      },
      {
        id: 86,
        name: 'Dove Deodorant',
        primary_picture: 'https://picsum.photos/300',
        description: 'Soothing cucumber scent deodorant',
        price: '7',
      },
      {
        id: 87,
        name: 'Aveeno Daily Moisturizing Lotion',
        primary_picture: 'https://picsum.photos/300',
        description: 'Gentle, fragrance-free body lotion',
        price: '8',
      },
      {
        id: 88,
        name: 'OGX Coconut Shampoo and Conditioner',
        primary_picture: 'https://picsum.photos/300',
        description: 'Nourishing coconut milk shampoo and conditioner',
        price: '9',
      },
      {
        id: 89,
        name: 'Degree Men Antiperspirant Deodorant',
        primary_picture: 'https://picsum.photos/300',
        description: 'Deodorant providing 48-hour sweat protection',
        price: '4',
      },
      {
        id: 90,
        name: 'Aquaphor Healing Ointment',
        primary_picture: 'https://picsum.photos/300',
        description: 'Multipurpose moisturizing skin protectant',
        price: '8',
      },
    ],
  },
  {
    'Baby Products': [
      {
        id: 91,
        name: 'Pampers Swaddlers Diapers',
        primary_picture: 'https://picsum.photos/300',
        description: 'Gentle, blanket-soft diapers',
        price: '25',
      },
      {
        id: 92,
        name: "Graco Pack 'n Play",
        primary_picture: 'https://picsum.photos/300',
        description: 'Portable crib and playard for baby',
        price: '170',
      },
      {
        id: 93,
        name: 'Infantino Baby Carrier',
        primary_picture: 'https://picsum.photos/300',
        description: 'Ergonomic cotton baby wrap carrier',
        price: '40',
      },
      {
        id: 94,
        name: 'VTech Sit-to-Stand Learning Walker',
        primary_picture: 'https://picsum.photos/300',
        description: 'Interactive baby walker that grows with child',
        price: '35',
      },
      {
        id: 95,
        name: "Fisher-price Kick 'n Play Piano",
        primary_picture: 'https://picsum.photos/300',
        description: 'Activity gym, piano & toddler play mat',
        price: '40',
      },
      {
        id: 96,
        name: 'Baby Einstein Learning Toys',
        primary_picture: 'https://picsum.photos/300',
        description: 'Building blocks to develop motor & cognitive skills',
        price: '15',
      },
      {
        id: 97,
        name: 'Medela Breast Pumps',
        primary_picture: 'https://picsum.photos/300',
        description: 'Efficient and comfortable breast pumps',
        price: '150',
      },
      {
        id: 98,
        name: 'Baby Bjorn Bouncer',
        primary_picture: 'https://picsum.photos/300',
        description: 'Ergonomic baby bouncer with natural rocking motion',
        price: '200',
      },
      {
        id: 99,
        name: 'Baby Monitor by VTech DM111',
        primary_picture: 'https://picsum.photos/300',
        description: 'Digital video baby monitor with night vision & talkback',
        price: '35',
      },
      {
        id: 100,
        name: 'Baby Banana Teething Toothbrush',
        primary_picture: 'https://picsum.photos/300',
        description: 'Gentle silicone brush for baby teething relief',
        price: '8',
      },
      {
        id: 101,
        name: 'Baby Bottles by Philips Avent',
        primary_picture: 'https://picsum.photos/300',
        description: 'BPA-free baby bottles for natural feeding',
        price: '20',
      },
      {
        id: 102,
        name: 'Baby Einstein Take Along Tunes',
        primary_picture: 'https://picsum.photos/300',
        description: 'Interactive toy with lights, sounds & music',
        price: '15',
      },
    ],
  },
  {
    Gaming: [
      {
        id: 103,
        name: 'PlayStation 5',
        primary_picture: 'https://picsum.photos/300',
        description: 'Next-gen gaming console by Sony',
        price: '499',
      },
      {
        id: 104,
        name: 'Xbox Series X',
        primary_picture: 'https://picsum.photos/300',
        description: 'Powerful gaming console by Microsoft',
        price: '499',
      },
      {
        id: 105,
        name: 'Nintendo Switch',
        primary_picture: 'https://picsum.photos/300',
        description: 'Hybrid gaming console for home and on-the-go play',
        price: '299',
      },
      {
        id: 106,
        name: 'Logitech G Pro X Mechanical Gaming Keyboard',
        primary_picture: 'https://picsum.photos/300',
        description: 'Compact mechanical gaming keyboard',
        price: '149',
      },
      {
        id: 107,
        name: 'SteelSeries Arctis 7 Wireless Gaming Headset',
        primary_picture: 'https://picsum.photos/300',
        description: 'Lag-free wireless gaming headset',
        price: '149',
      },
      {
        id: 108,
        name: 'Razer DeathAdder Elite Gaming Mouse',
        primary_picture: 'https://picsum.photos/300',
        description: 'High-precision gaming mouse',
        price: '69',
      },
      {
        id: 109,
        name: 'ASUS ROG Swift PG279Q Gaming Monitor',
        primary_picture: 'https://picsum.photos/300',
        description: '27-inch WQHD gaming monitor with IPS panel',
        price: '699',
      },
      {
        id: 110,
        name: 'Corsair HS70 Pro Wireless Gaming Headset',
        primary_picture: 'https://picsum.photos/300',
        description: 'Wireless gaming headset with 7.1 surround sound',
        price: '89',
      },
      {
        id: 111,
        name: 'Nintendo Switch Pro Controller',
        primary_picture: 'https://picsum.photos/300',
        description: 'High-performance wireless controller for Nintendo Switch',
        price: '69',
      },
      {
        id: 112,
        name: 'WD_BLACK 2TB P10 Game Drive',
        primary_picture: 'https://picsum.photos/300',
        description: 'Portable external hard drive for gaming',
        price: '79',
      },
      {
        id: 113,
        name: 'Elgato HD60 S Capture Card',
        primary_picture: 'https://picsum.photos/300',
        description: 'External capture card for streaming and recording',
        price: '179',
      },
      {
        id: 114,
        name: 'HyperX Cloud II Gaming Headset',
        primary_picture: 'https://picsum.photos/300',
        description: 'Wired gaming headset with 7.1 surround sound',
        price: '99',
      },
    ],
  },
  {
    'Sporting Goods': [
      {
        id: 115,
        name: 'Wilson Evolution Basketball',
        primary_picture: 'https://picsum.photos/300',
        description: 'Intermediate outdoor and indoor basketball',
        price: '50',
      },
      {
        id: 116,
        name: 'Nike SuperRep Go 2 Training Shoes',
        primary_picture: 'https://picsum.photos/300',
        description: 'Versatile workout shoes for cardio and HIIT',
        price: '120',
      },
      {
        id: 117,
        name: 'Under Armour RUSHTM Long Sleeve',
        primary_picture: 'https://picsum.photos/300',
        description: 'Quick-drying, anti-odor base layer shirt',
        price: '55',
      },
      {
        id: 118,
        name: 'Adidas Alphabounce+ Running Shoes',
        primary_picture: 'https://picsum.photos/300',
        description: 'Lightweight cushioned shoes for runners',
        price: '85',
      },
      {
        id: 119,
        name: 'NordicTrack Commercial 2950 Treadmill',
        primary_picture: 'https://picsum.photos/300',
        description: 'High performance treadmill with 22-inch display',
        price: '2999',
      },
      {
        id: 120,
        name: 'Traditional Wooden Yoga Blocks',
        primary_picture: 'https://picsum.photos/300',
        description: 'Set of 2 sanded wood yoga blocks',
        price: '16',
      },
      {
        id: 121,
        name: 'Gaiam Yoga Mat',
        primary_picture: 'https://picsum.photos/300',
        description: 'Print extra thick non-slip exercise yoga mat',
        price: '35',
      },
      {
        id: 122,
        name: 'Gatorade Sports Drink',
        primary_picture: 'https://picsum.photos/300',
        spec: ['Orange', 'Fruit Punch', 'Lemon Lime'],
        description: 'Thirst quenching sports performance drink',
        price: '15',
      },
      {
        id: 123,
        name: 'TaylorMade M6 Driver',
        primary_picture: 'https://picsum.photos/300',
        spec: ['Regular', 'Stiff Flex'],
        description: 'Adjustable golf driver for forgiveness and distance',
        price: '429',
      },
      {
        id: 124,
        name: 'Spalding NBA Street Basketball',
        primary_picture: 'https://picsum.photos/300',
        description: 'Outdoor composite leather basketball',
        price: '25',
      },
      {
        id: 125,
        name: 'Nike Downshifter 11 Running Shoes',
        primary_picture: 'https://picsum.photos/300',
        description: 'Cushioned shoes for road running',
        price: '65',
      },
      {
        id: 126,
        name: 'Body Solid Strength Training Equipment',
        primary_picture: 'https://picsum.photos/300',
        description: 'Multi-station home gym weight machine',
        price: '2995',
      },
    ],
  },
  {
    Automobile: [
      {
        id: 127,
        name: 'Toyota Camry',
        primary_picture: 'https://picsum.photos/300',
        description: 'Reliable, efficient midsize sedan',
        price: '27,925',
      },
      {
        id: 128,
        name: 'Ford F-150',
        primary_picture: 'https://picsum.photos/300',
        description: "America's best-selling pickup truck",
        price: '32,659',
      },
      {
        id: 129,
        name: 'Honda Civic',
        primary_picture: 'https://picsum.photos/300',
        description: 'Practical compact car that is fun to drive',
        price: '24,095',
      },
      {
        id: 130,
        name: 'Tesla Model 3',
        primary_picture: 'https://picsum.photos/300',
        description: 'Electric sedan with sharp styling and 310+ mile range',
        price: '46,990',
      },
      {
        id: 131,
        name: 'Jeep Wrangler',
        primary_picture: 'https://picsum.photos/300',
        description: 'Iconic off-roader with removable top and doors',
        price: '29,440',
      },
      {
        id: 132,
        name: 'Nissan Altima',
        primary_picture: 'https://picsum.photos/300',
        description: 'Sporty and stylish midsize sedan',
        price: '25,395',
      },
      {
        id: 133,
        name: 'Toyota RAV4',
        primary_picture: 'https://picsum.photos/300',
        description: 'One of the most popular compact SUVs',
        price: '27,245',
      },
      {
        id: 134,
        name: 'Honda Accord',
        primary_picture: 'https://picsum.photos/300',
        description: 'Spacious sedan with excellent resale value',
        price: '26,370',
      },
      {
        id: 135,
        name: 'BMW 3 Series',
        primary_picture: 'https://picsum.photos/300',
        description: 'Iconic compact luxury sedan',
        price: '43,000',
      },
      {
        id: 136,
        name: 'Ford Escape',
        primary_picture: 'https://picsum.photos/300',
        description: 'Fun driving crossover SUV',
        price: '26,510',
      },
      {
        id: 137,
        name: 'Chevrolet Silverado',
        primary_picture: 'https://picsum.photos/300',
        description: 'Strong, dependable, full-size truck',
        price: '33,695',
      },
      {
        id: 138,
        name: 'Toyota Corolla',
        primary_picture: 'https://picsum.photos/300',
        description: 'Economical and reliable compact sedan',
        price: '21,472',
      },
    ],
  },
];

export default function getItems(category) {
  if (category.toLowerCase() === 'others') {
    return products.reduce((allItems, currentCategory) => {
      const currentItems = Object.values(currentCategory)[0];
      return allItems.concat(currentItems);
    }, []);
  } else {
    const selectedCategory = products.find(cat => Object.keys(cat)[0].toLowerCase() === category.toLowerCase());
    return selectedCategory ? Object.values(selectedCategory)[0] : [];
  }
}
